insert into customer (name, city) values ('Jackie McReidy', 'Laojun');
insert into customer (name, city) values ('Keelia Dwire', 'Miami');
insert into customer (name, city) values ('Nikola Aspinall', 'Bella Vista');
insert into customer (name, city) values ('Barrie Tainton', 'Saurama');
insert into customer (name, city) values ('Rebbecca Wernham', 'Xiaocun');
insert into customer (name, city) values ('Alic Maskall', 'Krajan Gading');
insert into customer (name, city) values ('Humphrey Storms', 'Sepolong Timur');
insert into customer (name, city) values ('Martita Normandale', 'Arroio do Meio');
insert into customer (name, city) values ('Melisande Cottis', 'Loutrá');
insert into customer (name, city) values ('Alfons Boyall', 'Uzhhorod');
insert into customer (name, city) values ('Carlota Radnage', 'Sernovodsk');
insert into customer (name, city) values ('Joey Olyff', 'Bihoro');
insert into customer (name, city) values ('Alissa Sealeaf', 'Upper San Mateo');
insert into customer (name, city) values ('Bastian Gissing', 'Cikajang');
insert into customer (name, city) values ('August Dymocke', 'Igbeti');
insert into customer (name, city) values ('Sylas Stead', 'Ciechanów');
insert into customer (name, city) values ('Lorinda Senecaux', 'Caramanta');
insert into customer (name, city) values ('Nicolea Ernshaw', 'Jianshe');
insert into customer (name, city) values ('Dore Giacomo', 'Wates');
insert into customer (name, city) values ('Garwood Sabater', 'Ta Phraya');
insert into customer (name, city) values ('Bret Hagley', 'Huasahuasi');
insert into customer (name, city) values ('Durante Peche', 'El Refugio');
insert into customer (name, city) values ('Zed Kilford', 'Katipunan');
insert into customer (name, city) values ('Elwira Cant', 'Huanchillas');
insert into customer (name, city) values ('Gus Rosenvasser', 'Taihe');
insert into customer (name, city) values ('Shay Foxen', 'Kivertsi');
insert into customer (name, city) values ('Bobbie Kleimt', 'Antipolo');
insert into customer (name, city) values ('Halsey Grzegorecki', 'Guifões');
insert into customer (name, city) values ('Davey Dickin', 'Shūsh');
insert into customer (name, city) values ('Alister Grzegorczyk', 'Leitões');
insert into customer (name, city) values ('Sergent Aries', 'Nangkaruka');
insert into customer (name, city) values ('Natka Yven', 'Adrasmon');
insert into customer (name, city) values ('Trev Agiolfinger', 'Shekou');
insert into customer (name, city) values ('Phillis Lumsdale', 'Quinta da Courela');
insert into customer (name, city) values ('Farra Menichi', 'Luso');
insert into customer (name, city) values ('Liuka Burnsall', 'Cotabato');
insert into customer (name, city) values ('Jedidiah Gabbot', 'Taupo');
insert into customer (name, city) values ('Englebert Rees', 'Rodolívos');
insert into customer (name, city) values ('Ramsey Houlton', 'Brodokalmak');
insert into customer (name, city) values ('Florance Stedell', 'Ouro Branco');
insert into customer (name, city) values ('Geri Akers', 'San Juan');
insert into customer (name, city) values ('Gibby Dakhno', 'El Pino');
insert into customer (name, city) values ('Janka Wannell', 'Huazangsi');
insert into customer (name, city) values ('Murielle Glidder', 'Santa Luzia');
insert into customer (name, city) values ('Melva Roglieri', 'Douane');
insert into customer (name, city) values ('Katherine Strutz', 'Turus');
insert into customer (name, city) values ('Herbert Halahan', 'Smolyan');
insert into customer (name, city) values ('Jabez Hightown', 'Mladá Boleslav');
insert into customer (name, city) values ('Ambrosi Pluck', 'Khlong Hat');
insert into customer (name, city) values ('Tam Crow', 'Lümeng');
insert into customer (name, city) values ('Dinny Yakebovich', 'Macapá');
insert into customer (name, city) values ('Artemis Brimilcombe', 'Uppsala');
insert into customer (name, city) values ('Rasia Mathelon', 'Firavitoba');
insert into customer (name, city) values ('Waylon Andor', 'Jiaotan');
insert into customer (name, city) values ('Levy Waleworke', 'Castañas');
insert into customer (name, city) values ('Ainslie Proctor', 'Osasco');
insert into customer (name, city) values ('Jacquette Binestead', 'Sungailiat');
insert into customer (name, city) values ('Nil Leidl', 'Bender');
insert into customer (name, city) values ('Glyn Durham', 'Vientiane');
insert into customer (name, city) values ('Bellanca Caukill', 'Casal do Relvas');
insert into customer (name, city) values ('Caressa Cisland', 'Punta Gorda');
insert into customer (name, city) values ('Merle Doudney', 'Tunggulsari');
insert into customer (name, city) values ('Jareb Chestney', 'Bājitpur');
insert into customer (name, city) values ('Jerald Blenkinsopp', 'Ash Shiḩr');
insert into customer (name, city) values ('Riley Double', 'Siuna');
insert into customer (name, city) values ('Auria Leinweber', 'Piedecuesta');
insert into customer (name, city) values ('Tomasine Dodman', 'Druju');
insert into customer (name, city) values ('Harrietta Hawford', 'San Luis');
insert into customer (name, city) values ('Adelheid Dyson', 'Darłowo');
insert into customer (name, city) values ('Hardy Station', 'Pangkajene');
insert into customer (name, city) values ('Daryl Lytell', 'Gondomar');
insert into customer (name, city) values ('Stace Leisk', 'Kankara');
insert into customer (name, city) values ('Frederic Stivens', 'Siak Sri Indrapura');
insert into customer (name, city) values ('Roseline Doswell', 'Xiaoshanzi');
insert into customer (name, city) values ('Adria Ewen', 'Suita');
insert into customer (name, city) values ('Mattie Helbeck', 'Joutseno');
insert into customer (name, city) values ('Florri GiacobbiniJacob', 'Sirāhā');
insert into customer (name, city) values ('Fay Jeannon', 'Citarik');
insert into customer (name, city) values ('Gordan Saffle', 'Gorbatov');
insert into customer (name, city) values ('Obadiah Boswell', 'Casal dos Bernardos');
insert into customer (name, city) values ('Gabriele Lammas', 'Bacem');
insert into customer (name, city) values ('Melony Jendrich', 'Åby');
insert into customer (name, city) values ('Agnesse Liston', 'Ariquemes');
insert into customer (name, city) values ('Arlie Howbrook', 'Ban Phaeo');
insert into customer (name, city) values ('Cullen Boost', 'Linköping');
insert into customer (name, city) values ('Bil Toffolo', 'Yamparáez');
insert into customer (name, city) values ('Dion Meaton', 'Zasip');
insert into customer (name, city) values ('Jasper Ginty', 'Tigarunggu');
insert into customer (name, city) values ('Angil Guillford', 'Shahrud');
insert into customer (name, city) values ('Octavius Dolphin', 'An Nāşirah');
insert into customer (name, city) values ('Gerhardine Kelmere', 'Sandnes');
insert into customer (name, city) values ('Creighton Morigan', 'Hingatungan');
insert into customer (name, city) values ('Cleavland Causnett', 'Saint-Denis');
insert into customer (name, city) values ('Perice Shevill', 'Guanshan');
insert into customer (name, city) values ('Kiri Plumbridge', 'Horní Lideč');
insert into customer (name, city) values ('Patrice Halfhide', 'Thị Trấn Sìn Hồ');
insert into customer (name, city) values ('Ladonna Druhan', 'Spanish Wells');
insert into customer (name, city) values ('Bernetta Baseley', 'Lattes');
insert into customer (name, city) values ('Kania Jobson', 'Paccha');
insert into customer (name, city) values ('Gwendolen Winn', 'Sherpur');
insert into customer (name, city) values ('Lyndell Bertomieu', 'Sanxi');
insert into customer (name, city) values ('Bobbi Frizell', 'Xiaogang');
insert into customer (name, city) values ('Xerxes Bartholin', 'Lamas');
insert into customer (name, city) values ('Jacklin Schwier', 'Kuripan');
insert into customer (name, city) values ('Freddie Duinbleton', 'Karpacz');
insert into customer (name, city) values ('Ula McTeague', 'Yong’an');
insert into customer (name, city) values ('Claus Lansley', 'São Mateus');
insert into customer (name, city) values ('Blair Beddows', 'Goubangzi');
insert into customer (name, city) values ('Celisse Slowgrave', 'Llauta');
insert into customer (name, city) values ('Tessi Twigley', 'Neuville');
insert into customer (name, city) values ('Michail Thompson', 'Talugtug');
insert into customer (name, city) values ('Richmound Bolden', 'Tertek');
insert into customer (name, city) values ('Christoffer Balcombe', 'Miras');
insert into customer (name, city) values ('Carrie Duggan', 'Shireet');
insert into customer (name, city) values ('Hamel Crufts', 'Arrabal');
insert into customer (name, city) values ('Brock Turvey', 'Hepu');
insert into customer (name, city) values ('Fran Peirazzi', 'Lab');
insert into customer (name, city) values ('Alan Ginnety', 'Vales');
insert into customer (name, city) values ('Kalil Braune', 'Khenifra');
insert into customer (name, city) values ('Ora Oliver', 'Tanjungbahagia');
insert into customer (name, city) values ('Concettina Garmans', 'Dayou');
insert into customer (name, city) values ('Lock Neno', 'Kabala');
insert into customer (name, city) values ('Christian Woolaghan', 'Gwangju');
insert into customer (name, city) values ('Kalinda Kinneally', 'Dugulubgey');
insert into customer (name, city) values ('Kessiah Rickertsen', 'Lixu');
insert into customer (name, city) values ('Jeddy Tugwell', 'Baitouli');
insert into customer (name, city) values ('Joyann Dunbabin', 'Oro Verde');
insert into customer (name, city) values ('Cristie Meriott', 'Cilongkrangpusaka');
insert into customer (name, city) values ('Keane Wiltsher', 'Banjar Anyar');
insert into customer (name, city) values ('Zorina Beak', 'Senahú');
insert into customer (name, city) values ('Mikkel Farahar', 'Dangjiaxian');
insert into customer (name, city) values ('Barbee Stonebanks', 'Jamao al Norte');
insert into customer (name, city) values ('Laraine Hards', 'Uijeongbu-si');
insert into customer (name, city) values ('Rube Algar', 'Janów');
insert into customer (name, city) values ('Sarajane Orrah', 'Jardim da Serra');
insert into customer (name, city) values ('Ronnica Coulsen', 'Nuku‘alofa');
insert into customer (name, city) values ('Tait Maidment', 'Qingquan');
insert into customer (name, city) values ('Ruby Caherny', 'Hội An');
insert into customer (name, city) values ('Donny Galton', 'Aga');
insert into customer (name, city) values ('Adan Pimlett', 'Blatnica');
insert into customer (name, city) values ('Tiff McGilbon', 'Mae Lao');
insert into customer (name, city) values ('Zollie Watkiss', 'Nor Yerznka');
insert into customer (name, city) values ('Stanislaus McAnellye', 'Adare');
insert into customer (name, city) values ('Jamal Mirando', 'Bakaran Kulon');
insert into customer (name, city) values ('Mandie Heartfield', 'Cap Malheureux');
insert into customer (name, city) values ('Cyb Glidder', 'Toride');
insert into customer (name, city) values ('Ronald Wildbore', 'Valladolid');
insert into customer (name, city) values ('Celene De Simone', 'Ol’ginskaya');
insert into customer (name, city) values ('Thadeus Belchem', 'Yongfu');
insert into customer (name, city) values ('Oralla Gauge', 'Goworowo');
insert into customer (name, city) values ('Farrell Pasek', 'Potiskum');
insert into customer (name, city) values ('Mommy Redmain', 'Rukunlima Bawah');
insert into customer (name, city) values ('Portia Butcher', 'Tadrart');
insert into customer (name, city) values ('Aggi Inkin', 'Solingen');
insert into customer (name, city) values ('Joya Heino', 'Capalonga');
insert into customer (name, city) values ('Regen Clemenzi', 'Vila Viçosa');
insert into customer (name, city) values ('Ilse Bresnahan', 'Jialu');
insert into customer (name, city) values ('Kristel Lemme', 'Yashio-shi');
insert into customer (name, city) values ('Renell Ringe', 'Hamburg');
insert into customer (name, city) values ('Scarlett Caig', 'Tamansari');
insert into customer (name, city) values ('Jacob Hinkes', 'Rio Branco');
insert into customer (name, city) values ('Pennie Derisley', 'Le Tampon');
insert into customer (name, city) values ('Alexia Hynde', 'Chigang');
insert into customer (name, city) values ('Chaim Harragin', 'Kazanlŭk');
insert into customer (name, city) values ('Nita Scimonelli', 'Hangbu');
insert into customer (name, city) values ('Tamarra Folks', 'Villa Carlos Paz');
insert into customer (name, city) values ('Merlina Kinver', 'Lagawe');
insert into customer (name, city) values ('Culver Myton', 'Ngedhubasa');
insert into customer (name, city) values ('Nat Benjafield', 'Kebon');
insert into customer (name, city) values ('Valaria Robun', 'Rawang');
insert into customer (name, city) values ('Jeremie Fevier', 'Puerto Ayacucho');
insert into customer (name, city) values ('Dale Spiniello', 'Curug');
insert into customer (name, city) values ('Freida Ellicock', 'Sangatta');
insert into customer (name, city) values ('Jamil Sorrell', 'Diadema');
insert into customer (name, city) values ('Claresta Bosman', 'Twante');
insert into customer (name, city) values ('Reagen Labbey', 'London');
insert into customer (name, city) values ('Glynn Keunemann', 'Cuntan');
insert into customer (name, city) values ('Kriste Caccavella', 'Ake-Eze');
insert into customer (name, city) values ('Dill Anders', 'Causip');
insert into customer (name, city) values ('Garnet Ilyenko', 'Qujiang');
insert into customer (name, city) values ('Jeanine Mahmood', 'Munka-Ljungby');
insert into customer (name, city) values ('Reagan Pestor', 'Pondokdalem');
insert into customer (name, city) values ('Erina Tharme', 'San Jose');
insert into customer (name, city) values ('Janeta Reoch', 'Wang Sam Mo');
insert into customer (name, city) values ('Davidde Archer', 'Wuxiang');
insert into customer (name, city) values ('Gerick Van der Velde', 'Segezha');
insert into customer (name, city) values ('Layne McCall', 'Skotoússa');
insert into customer (name, city) values ('Gaspard Joisce', 'Nong Khae');
insert into customer (name, city) values ('Bruno Clarridge', 'Bangshipu');
insert into customer (name, city) values ('Stefania Joddens', 'Rangpur');
insert into customer (name, city) values ('Lauraine Eastwood', 'Daytona Beach');
insert into customer (name, city) values ('Stephan Gavagan', 'Sarrat');
insert into customer (name, city) values ('Maiga Osgordby', 'Kerema');
insert into customer (name, city) values ('Eilis Brodhead', 'Ush-Tyube');
insert into customer (name, city) values ('Selena Leveritt', 'Qal‘ah-ye Fārsī');
insert into customer (name, city) values ('Tomlin Safe', 'Pigeiros');
insert into customer (name, city) values ('Karlis Tortoishell', 'Vallentuna');
insert into customer (name, city) values ('Keri Oiseau', 'Litan');
insert into customer (name, city) values ('Yance Zapater', 'Sukawening');
insert into customer (name, city) values ('Coleen Link', 'Kolomyya');
insert into customer (name, city) values ('Danie Vaughton', 'Novoselë');
insert into customer (name, city) values ('Emelina Comar', 'Klwów');
insert into customer (name, city) values ('Vivien Freiberg', 'Spartanburg');
insert into customer (name, city) values ('Brooks Castellaccio', 'Quisao');
insert into customer (name, city) values ('Erastus Dowall', 'Pasadena');
insert into customer (name, city) values ('Shay Saby', 'Lutun');
insert into customer (name, city) values ('Ethelda Hasser', 'Venilale');
insert into customer (name, city) values ('Stacy Strangward', 'Nangka');
insert into customer (name, city) values ('Ame Collyer', 'Tabio');
insert into customer (name, city) values ('Cory Orchard', 'Balkh');
insert into customer (name, city) values ('Joelly Reditt', 'Karlskoga');
insert into customer (name, city) values ('Farris Riquet', 'Sydney');
insert into customer (name, city) values ('Amalie Quade', 'Pandansari');
insert into customer (name, city) values ('Ailis Whitemarsh', 'Bella Vista');
insert into customer (name, city) values ('Pauly Ingleson', 'Zhaogezhuang');
insert into customer (name, city) values ('Huberto Castanie', 'Boston');
insert into customer (name, city) values ('Lamar Parres', 'Launceston');
insert into customer (name, city) values ('Pierette Sherewood', 'Villa Paula de Sarmiento');
insert into customer (name, city) values ('Drusilla Kellen', 'Quatá');
insert into customer (name, city) values ('Shandie Apark', 'Nariño');
insert into customer (name, city) values ('Clarine Styant', 'Rogoźnik');
insert into customer (name, city) values ('Sondra Mickleborough', 'Puente Alto');
insert into customer (name, city) values ('Daryl Skevington', 'Zhengdun');
insert into customer (name, city) values ('Tansy Sebert', 'San Marcos');
insert into customer (name, city) values ('Ashby Ganniclifft', 'Zhetang');
insert into customer (name, city) values ('Inger Ivimey', 'Mthatha');
insert into customer (name, city) values ('Wilone Collete', 'Krajan Menggare');
insert into customer (name, city) values ('Conrado Minear', 'Voorburg');
insert into customer (name, city) values ('Dorelle Bangs', 'Sayyān');
insert into customer (name, city) values ('Kalila Moro', 'Tyret’ Pervaya');
insert into customer (name, city) values ('Brittani Stroton', 'Honolulu');
insert into customer (name, city) values ('Junette Oxford', 'Xianghu');
insert into customer (name, city) values ('Debbi Kivlin', 'Eger');
insert into customer (name, city) values ('Dodie Gawn', 'Taywanak Ilaya');
insert into customer (name, city) values ('Kassandra Common', 'Ciawitali');
insert into customer (name, city) values ('Jackson Le Bosse', 'Mohale’s Hoek');
insert into customer (name, city) values ('Merla Dunphy', '‘Ajlūn');
insert into customer (name, city) values ('Jeane Panons', 'Frederiksberg');
insert into customer (name, city) values ('Anson Gianni', 'Youdian');
insert into customer (name, city) values ('Dot Perryman', 'Batukuta');
insert into customer (name, city) values ('Orel Bidnall', 'Orikhiv');
insert into customer (name, city) values ('Jayson Fielders', 'Charyshskoye');
insert into customer (name, city) values ('Linette Pennycook', 'Poja Nae');
insert into customer (name, city) values ('Ashia Hallowell', 'Magallanes');
insert into customer (name, city) values ('Ingaborg Cambridge', 'Boro');
insert into customer (name, city) values ('Clerissa Zebedee', 'Cisewu');
insert into customer (name, city) values ('Drusy Gasnell', 'Aydūn');
insert into customer (name, city) values ('Merwin Persence', 'Xishaping');
insert into customer (name, city) values ('Iolande Enbury', 'Metlika');
insert into customer (name, city) values ('Philip Spohrmann', 'Sidi Bousber');
insert into customer (name, city) values ('Jeralee Franzotto', 'Ibaté');
insert into customer (name, city) values ('Hillel Prowting', 'Singabarong');
insert into customer (name, city) values ('Opaline Hull', 'Kramarzówka');
insert into customer (name, city) values ('Peyton MacNab', 'Calauan');
insert into customer (name, city) values ('Charity Gapper', 'Lingmen');
insert into customer (name, city) values ('Heall Marciek', 'Oelaba');
insert into customer (name, city) values ('Berti Le Borgne', 'Tongxing');
insert into customer (name, city) values ('Marcelline Spier', 'Banepa');
insert into customer (name, city) values ('Evered Torritti', 'Beselga');
insert into customer (name, city) values ('Warren Darragon', 'Pámfylla');
insert into customer (name, city) values ('Lyssa Strowan', 'Ambarakaraka');
insert into customer (name, city) values ('Essy McGilvary', 'Yuanda');
insert into customer (name, city) values ('Robbert Cumberbatch', 'Oenunu');
insert into customer (name, city) values ('Meyer Hughill', 'Dolna Banjica');
insert into customer (name, city) values ('Dorene Gentiry', 'Xiagang');
insert into customer (name, city) values ('Chickie Brannon', 'Shiye');
insert into customer (name, city) values ('Melba Bramble', 'Ying’ebu');
insert into customer (name, city) values ('Sam Dubois', 'Verkh-Usugli');
insert into customer (name, city) values ('Cass Trodler', 'Višnjevac');
insert into customer (name, city) values ('Noella Reede', 'Fonte Boa');
insert into customer (name, city) values ('Ryon Straniero', 'Longping');
insert into customer (name, city) values ('Morgana Espinho', 'Saint Croix');
insert into customer (name, city) values ('Janet Byng', 'Ivatsevichy');
insert into customer (name, city) values ('Gris Billings', 'Podgorica');
insert into customer (name, city) values ('Doug Vannoni', 'Bohus');
insert into customer (name, city) values ('Neill Jessett', 'Dvin');
insert into customer (name, city) values ('Abe McColley', 'Benešov nad Černou');
insert into customer (name, city) values ('Bobby Barok', 'Ojos de Agua');
insert into customer (name, city) values ('Jacques Mangenot', 'Cradock');
insert into customer (name, city) values ('Belinda Sievewright', 'Pokhvistnevo');
insert into customer (name, city) values ('Dore Corneljes', 'Cangzhou');
insert into customer (name, city) values ('Mil Heasley', 'Mintang');
insert into customer (name, city) values ('Evyn Castagnaro', 'Neebing');
insert into customer (name, city) values ('Brandie Hatry', 'Xam Nua');
insert into customer (name, city) values ('Eilis Gorling', 'Qui Nhon');
insert into customer (name, city) values ('Brendan Bontine', 'Loandjili');
insert into customer (name, city) values ('Alameda McGrory', 'Mattawa');
insert into customer (name, city) values ('Romona Hedley', 'Paris 13');
insert into customer (name, city) values ('Hort Seefeldt', 'Nankeng');
insert into customer (name, city) values ('Ardelle Chang', 'Saint-Étienne');
insert into customer (name, city) values ('Sauncho Pepon', 'Zhangjiabao');
insert into customer (name, city) values ('Lydie Gooley', 'Pyatnitskoye');
insert into customer (name, city) values ('Beverley Betjes', 'Leiden');
insert into customer (name, city) values ('Domenico Tranter', 'Tampekan');
insert into customer (name, city) values ('Raynell Holleworth', 'Nekla');
insert into customer (name, city) values ('Chrissy Merveille', 'Geneng');
insert into customer (name, city) values ('Berty Clymo', 'Banaran');
insert into customer (name, city) values ('Matthieu Cornford', 'Nanhe');
insert into customer (name, city) values ('Dana D''Aulby', 'Jatake');
insert into customer (name, city) values ('Kissee Fold', 'Pasiripis');
insert into customer (name, city) values ('Lyda Vere', 'Torres Vedras');
insert into customer (name, city) values ('Koressa Boarleyson', 'Portão');
insert into customer (name, city) values ('Zuzana Friett', 'Reims');
insert into customer (name, city) values ('Patrica Danniell', 'Ekasapta');
insert into customer (name, city) values ('Mavra McMurrugh', 'Turki');
insert into customer (name, city) values ('Salim Yewdall', 'Héroumbili');
insert into customer (name, city) values ('Raine MacFall', 'Bābol');
insert into customer (name, city) values ('Beret Arthur', 'Putinci');
insert into customer (name, city) values ('Kissiah Canas', 'Sedinginan');
insert into customer (name, city) values ('Zonnya Tooting', 'Hāfizābād');
insert into customer (name, city) values ('Prent Gerauld', 'Călăraşi');
insert into customer (name, city) values ('Audry Pampling', 'Lidköping');
insert into customer (name, city) values ('Olenka Portress', 'Xintang');
insert into customer (name, city) values ('Jamey Trodden', 'Lavaltrie');
insert into customer (name, city) values ('Hendrick Judgkins', 'Burūm');
insert into customer (name, city) values ('Isa Eaklee', 'Bogo');
insert into customer (name, city) values ('Charles Blease', 'Starychi');
insert into customer (name, city) values ('Dietrich Ailmer', 'Saint John');
insert into customer (name, city) values ('Marja Bartell', 'Cungkal');
insert into customer (name, city) values ('Bondon Matthews', 'Köpingsvik');
insert into customer (name, city) values ('Maureen Skellern', 'Farsta');
insert into customer (name, city) values ('Bonni Thorns', 'Maripipi');
insert into customer (name, city) values ('Leon Meers', 'Halmstad');
insert into customer (name, city) values ('Wilow Lowdeane', 'Wujiao');
insert into customer (name, city) values ('Ole Gentiry', 'Jaru');
insert into customer (name, city) values ('Loralie Beaty', 'Fonte Boa');
insert into customer (name, city) values ('Ogdon Bonham', 'Carromeu');
insert into customer (name, city) values ('Valli Rendall', 'Tournavista');
insert into customer (name, city) values ('Christoffer Jeger', 'Liang');
insert into customer (name, city) values ('Emilio Maccraw', 'Gaya');
insert into customer (name, city) values ('Antonia Urvoy', 'Duobao');
insert into customer (name, city) values ('Baxie Rees', 'Jianshan');
insert into customer (name, city) values ('Wini Pennigar', 'Cabiguan');
insert into customer (name, city) values ('Siana Zold', 'Xi’an');
insert into customer (name, city) values ('Stacy Coppins', 'Nový Bydžov');
insert into customer (name, city) values ('Berte Vanderson', 'Vaitogi');
insert into customer (name, city) values ('Lyda Poynton', 'Vallentuna');
insert into customer (name, city) values ('Vivyan Ludovici', 'Barang');
insert into customer (name, city) values ('Kiersten Southwood', 'Heredia');
insert into customer (name, city) values ('Gina Scandrett', 'Banjar Bias');
insert into customer (name, city) values ('Agnella Packham', 'Morocelí');
insert into customer (name, city) values ('Bank Millichap', 'Głogówek');
insert into customer (name, city) values ('Catie Davenhill', 'Kidodi');
insert into customer (name, city) values ('Doralyn Tunnah', 'Clarin');
insert into customer (name, city) values ('Lenard Salzberg', 'Solna');
insert into customer (name, city) values ('Rea Roylance', 'Lapa');
insert into customer (name, city) values ('Carny Godman', 'Capitán Solari');
insert into customer (name, city) values ('Julia Ternott', 'San Jose');
insert into customer (name, city) values ('Gill Ollerenshaw', 'Randudongkal');
insert into customer (name, city) values ('Carlee Foot', 'Siekierczyn');
insert into customer (name, city) values ('Karel Mille', 'Lahuaytambo');
insert into customer (name, city) values ('Padgett Kiebes', 'Kupiskis');
insert into customer (name, city) values ('Lothaire Twitching', 'Lile');
insert into customer (name, city) values ('Dore Flieg', 'Bukor');
insert into customer (name, city) values ('Fedora Corkill', 'Chimanimani');
insert into customer (name, city) values ('Lauretta Rounsivall', 'Yarang');
insert into customer (name, city) values ('Aretha Custed', 'Karkkila');
insert into customer (name, city) values ('Darby Hacker', 'Goyty');
insert into customer (name, city) values ('Kassey Togwell', 'Orzu');
insert into customer (name, city) values ('Terrel Garter', 'Nueva Italia');
insert into customer (name, city) values ('Flem Spare', 'Añatuya');
insert into customer (name, city) values ('Carter Cuseick', 'Masipi West');
insert into customer (name, city) values ('Valentin Eddisforth', 'Isnos');
insert into customer (name, city) values ('Rowena Troppmann', 'Alkmaar');
insert into customer (name, city) values ('Brady Hyams', 'Siheyuan');
insert into customer (name, city) values ('Flory Perch', 'Boucinha');
insert into customer (name, city) values ('Legra Ziem', 'Hongsihu');
insert into customer (name, city) values ('Leila Elleton', 'Ålesund');
insert into customer (name, city) values ('Hart Pideon', 'Paris 16');
insert into customer (name, city) values ('Carey Aubrey', 'Sibay');
insert into customer (name, city) values ('Beryle McCuis', 'Gritsovskiy');
insert into customer (name, city) values ('Donal Joselson', 'Budayuan');
insert into customer (name, city) values ('Kienan Fynan', 'Vila Nova de Milfontes');
insert into customer (name, city) values ('Sibby Tropman', 'Besuki Dua');
insert into customer (name, city) values ('Lilli Sowter', 'Houxi');
insert into customer (name, city) values ('Deeyn Portwain', 'Turan');
insert into customer (name, city) values ('Legra Bienvenu', 'Derzhavīnsk');
insert into customer (name, city) values ('Nye Nono', 'Tokmok');
insert into customer (name, city) values ('Lonni Jeffcoate', 'Fonadhoo');
insert into customer (name, city) values ('Sascha Leemans', 'Danglang Hudong');
insert into customer (name, city) values ('Chet Rings', '20 de Noviembre');
insert into customer (name, city) values ('Layney Danilin', 'Debrecen');
insert into customer (name, city) values ('Robbie Rippingall', 'Rostokino');
insert into customer (name, city) values ('Ulrick Chamberlen', 'Xindi');
insert into customer (name, city) values ('Sigismond Crosfield', 'Ribafria');
insert into customer (name, city) values ('Davine Sutherington', 'Wengang');
insert into customer (name, city) values ('Laney Fosbraey', 'Parychy');
insert into customer (name, city) values ('Clarey Cleynaert', 'Xinwu');
insert into customer (name, city) values ('Demetris Childrens', 'Netanya');
insert into customer (name, city) values ('Tad Simpkins', 'Eustaquio Lopez');
insert into customer (name, city) values ('Janina Banister', 'Bakungan');
insert into customer (name, city) values ('Nicola Quiddihy', 'Täby');
insert into customer (name, city) values ('Claudie Eatock', 'Asahbadung');
insert into customer (name, city) values ('Cordy Ethelston', 'Örebro');
insert into customer (name, city) values ('Mina Buglass', 'Sanxi');
insert into customer (name, city) values ('Valerye Suckling', 'Keluke');
insert into customer (name, city) values ('June Bonehill', 'Mufulira');
insert into customer (name, city) values ('Claudette Echalie', 'Dumandesa');
insert into customer (name, city) values ('Blinnie Glowach', 'Bang Bon');
insert into customer (name, city) values ('Ariel Skyrme', 'Kitwe');
insert into customer (name, city) values ('Blanch Kernock', 'Talā');
insert into customer (name, city) values ('Humberto Phizakarley', 'Baltiysk');
insert into customer (name, city) values ('Jenica Harborow', 'Takahama');
insert into customer (name, city) values ('Thaine Kaming', 'Timiryazevskiy');
insert into customer (name, city) values ('Barth Molohan', 'Morrison');
insert into customer (name, city) values ('Roosevelt Shakespear', 'Shiḩan as Suflá');
insert into customer (name, city) values ('Danella Carey', 'Dobra');
insert into customer (name, city) values ('Fielding Mollnar', 'Acobamba');
insert into customer (name, city) values ('Alphonso Readwood', 'Concepcion');
insert into customer (name, city) values ('Elsbeth Norsworthy', 'Lembongan Kawan');
insert into customer (name, city) values ('Elsie Claxson', 'Tumba');
insert into customer (name, city) values ('Flori Pinard', 'Gornorechenskiy');
insert into customer (name, city) values ('Bunnie Walsh', 'Wuyahe');
insert into customer (name, city) values ('Vivianne Dower', 'Ijūin');
insert into customer (name, city) values ('Gavrielle Stobo', 'Zaqatala');
insert into customer (name, city) values ('Merilyn Peabody', 'Cisompet');
insert into customer (name, city) values ('Bobbette Boseley', 'Reshetikha');
insert into customer (name, city) values ('Vickie Mowsdell', 'San Bernardino');
insert into customer (name, city) values ('Lynn Mooreed', 'Karnice');
insert into customer (name, city) values ('Jethro Laughren', 'Yelkhovka');
insert into customer (name, city) values ('Sheilah Greest', 'Yosowilangun');
insert into customer (name, city) values ('Joachim Cratere', 'Muara');
insert into customer (name, city) values ('Dianna Whitcher', 'Dolice');
insert into customer (name, city) values ('Niles Mullarkey', 'Cagdianao');
insert into customer (name, city) values ('Tymon Lester', 'Abadiânia');
insert into customer (name, city) values ('Gretel Dewdney', 'Asan Kumbang');
insert into customer (name, city) values ('Gayler Parmiter', 'Iogach');
insert into customer (name, city) values ('Marcelo Fairlamb', 'Matangshan');
insert into customer (name, city) values ('Ralina Monteith', 'Fengyang');
insert into customer (name, city) values ('Willem Dignall', 'Facatativá');
insert into customer (name, city) values ('Devonne Meiklem', 'Gurra e Vogël');
insert into customer (name, city) values ('Abram Heap', 'Nūr');
insert into customer (name, city) values ('Laurice Allanson', 'Āqchah');
insert into customer (name, city) values ('Gwen Moreno', 'Anling');
insert into customer (name, city) values ('Udall Koba', 'Guanta');
insert into customer (name, city) values ('Petrina Royal', 'Pimbalayan');
insert into customer (name, city) values ('Leoine Silverton', 'Yuzawa');
insert into customer (name, city) values ('Rena Vanlint', 'Albany');
insert into customer (name, city) values ('Raffaello Fenney', 'Trnava');
insert into customer (name, city) values ('Joey Redwin', 'Uttar Char Fasson');
insert into customer (name, city) values ('Marty Skewes', 'Zhenghu');
insert into customer (name, city) values ('Theodosia Hardison', 'Manuel Cavazos Lerma');
insert into customer (name, city) values ('Lilian Spowage', 'Evansville');
insert into customer (name, city) values ('Blondelle Prickett', 'Sotomayor');
insert into customer (name, city) values ('Ethelin McElmurray', 'Penedo');
insert into customer (name, city) values ('Paige Mathy', 'Tangzi');
insert into customer (name, city) values ('Alix Ege', 'Nantuo');
insert into customer (name, city) values ('Maryanne Turley', 'Neikeng');
insert into customer (name, city) values ('Josi Chilles', 'Loma Bonita');
insert into customer (name, city) values ('Urbanus Queree', 'Mulatupo');
insert into customer (name, city) values ('Marquita Tosh', 'Camden');
insert into customer (name, city) values ('Dre Dady', 'Iradan');
insert into customer (name, city) values ('Aurel Tew', 'Libmanan');
insert into customer (name, city) values ('Herb Swafield', 'Los Cóndores');
insert into customer (name, city) values ('Linda Blose', 'Dulag');
insert into customer (name, city) values ('Concordia Bramich', 'Örebro');
insert into customer (name, city) values ('Hailee Mitkin', 'La Esperanza');
insert into customer (name, city) values ('Arlene Batrick', 'Rio Preto da Eva');
insert into customer (name, city) values ('Perri Illes', 'Yixingfu');
insert into customer (name, city) values ('Sadie Bardill', 'Az̧ Z̧a‘āyin');
insert into customer (name, city) values ('Augustine Havoc', 'Haradzishcha');
insert into customer (name, city) values ('Marylou Moss', 'Boissy-Saint-Léger');
insert into customer (name, city) values ('Tammy Gillbee', 'Nouaseur');
insert into customer (name, city) values ('Boris Schops', 'Piltown');
insert into customer (name, city) values ('Andrus Leechman', 'Cotorra');
insert into customer (name, city) values ('Catha Gunning', 'Petrolia');
insert into customer (name, city) values ('Britte Walch', 'Nkurenkuru');
insert into customer (name, city) values ('Sauveur Trythall', 'Regueiro');
insert into customer (name, city) values ('Elayne Doldon', 'Malunda');
insert into customer (name, city) values ('Alice Sweedland', 'Sampit');
insert into customer (name, city) values ('Regine Stead', 'Mar del Plata');
insert into customer (name, city) values ('Catharine McDermot', 'Shanting');
insert into customer (name, city) values ('Zerk Petken', 'Hînceşti');
insert into customer (name, city) values ('Sophey Fackrell', 'Sampit');
insert into customer (name, city) values ('Trefor Mazin', 'Santa Isabel');
insert into customer (name, city) values ('Darrin Bittlestone', 'Notsé');
insert into customer (name, city) values ('Shane Hof', 'Dongchuan');
insert into customer (name, city) values ('Osborne Aldus', 'Maoping');
insert into customer (name, city) values ('Web Barttrum', 'Maranganí');
insert into customer (name, city) values ('Jessie Lang', 'Airmolek');
insert into customer (name, city) values ('Ardelia Hatzar', 'Modosinal');
insert into customer (name, city) values ('Gaylene Gawith', 'Jinguoping');
insert into customer (name, city) values ('Montague Madders', 'Bilhó');
insert into customer (name, city) values ('Rivi Callington', 'Huaguoshan');
insert into customer (name, city) values ('Iolanthe Peabody', 'Fankeng');
insert into customer (name, city) values ('Olimpia Kordt', 'Randu');
insert into customer (name, city) values ('Rhetta Emons', 'Byumba');
insert into customer (name, city) values ('Marge Skey', 'Bjelovar');
insert into customer (name, city) values ('Calida Jaouen', 'Nakhon Sawan');
insert into customer (name, city) values ('Drake Conneau', 'Gaocun');
insert into customer (name, city) values ('Adelle Peter', 'Dalheim');
insert into customer (name, city) values ('Corilla Radnedge', 'Daye');
insert into customer (name, city) values ('Putnem McPhail', 'Kalinovskaya');
insert into customer (name, city) values ('Arden Leslie', 'Zalesnoye');
insert into customer (name, city) values ('Noland Tomaini', 'Gabi');
insert into customer (name, city) values ('Teodora Hrinchishin', 'Tanjungkerta');
insert into customer (name, city) values ('Nicoline Fittall', 'Oltintopkan');
insert into customer (name, city) values ('Keene Chesterman', 'Bolnisi');
insert into customer (name, city) values ('Jarid Jirieck', 'Gaotaizi');
insert into customer (name, city) values ('Berkie Dolton', 'Qŭrghontepa');
insert into customer (name, city) values ('Deerdre Steanyng', 'Lutoryż');
insert into customer (name, city) values ('Irena Dowle', 'Citasuk');
insert into customer (name, city) values ('Shauna Loseke', 'Gīvī');
insert into customer (name, city) values ('Wanda Robiou', 'Lillehammer');
insert into customer (name, city) values ('Reilly Lofthouse', 'Örbyhus');
insert into customer (name, city) values ('Amitie Emloch', 'Jiangcun');
insert into customer (name, city) values ('Carlos Friskey', 'El Refugio');
insert into customer (name, city) values ('Marge Iwaszkiewicz', 'Timrat');
insert into customer (name, city) values ('Cy Reicherz', 'Lagoa');
insert into customer (name, city) values ('Margy Millsap', 'Kombandaru');
insert into customer (name, city) values ('Padriac Lyddiard', 'Dankalwa');
insert into customer (name, city) values ('Gabi Juliano', 'Ourense');
insert into customer (name, city) values ('Corey Boddymead', 'Pātan');
insert into customer (name, city) values ('Ferris Kisbey', 'Straszydle');
insert into customer (name, city) values ('Raye Fosh', 'Hongkou');
insert into customer (name, city) values ('Albert Elijah', 'Fenghuanglu');
insert into customer (name, city) values ('Jefferson Danzey', 'Sriwing');
insert into customer (name, city) values ('Archer Benesevich', 'Gore');
insert into customer (name, city) values ('Kissiah Comerford', 'Dianya');
insert into customer (name, city) values ('Saxon Bockman', 'Växjö');
insert into customer (name, city) values ('Michal Hartshorn', 'Moutnice');
insert into customer (name, city) values ('Gunner Jonson', 'Busilak');
insert into customer (name, city) values ('Sauncho Burner', 'Villa La Angostura');
insert into customer (name, city) values ('Carlee Arthurs', 'Fakaifou Village');
insert into customer (name, city) values ('Jared Bosley', 'Limbalod');
insert into customer (name, city) values ('Carmen Proudlock', 'Tawaramoto');
insert into customer (name, city) values ('Piper Freen', 'Campamento');
insert into customer (name, city) values ('Koressa Learmonth', 'Minas de Marcona');
insert into customer (name, city) values ('Allayne Gotliffe', 'Abonnema');
insert into customer (name, city) values ('Diana Congreave', 'Klirou');
insert into customer (name, city) values ('Mabelle MacWilliam', 'Laylay');
insert into customer (name, city) values ('Gabe Fuchs', 'Bergamo');
insert into customer (name, city) values ('Sigmund Stannion', 'Saint-Jean-de-Monts');
insert into customer (name, city) values ('Conant Dureden', 'Tiemen');
insert into customer (name, city) values ('Darbee Erbain', 'Podol’sk');
insert into customer (name, city) values ('Arne Pailin', 'Putrajaya');
insert into customer (name, city) values ('Inger Abbiss', 'Pervoural’sk');
insert into customer (name, city) values ('Nev Waggatt', 'Sychëvo');
insert into customer (name, city) values ('Lee Carcas', 'Veles');
insert into customer (name, city) values ('Gerti Coursor', 'Awsīm');
insert into customer (name, city) values ('Aleece Dhenin', 'Italó');
insert into customer (name, city) values ('Rab Mort', 'Al Jaghbūb');
insert into customer (name, city) values ('Kristos Ludwell', 'Hankha');
insert into customer (name, city) values ('Doralyn Ratt', 'Calidñgan');
insert into customer (name, city) values ('Tamma Dondon', 'Guaiúba');
insert into customer (name, city) values ('Yorke Neising', 'Kremidivka');
insert into customer (name, city) values ('Mureil Maria', 'Mandaluyong City');
insert into customer (name, city) values ('Wilt Grinaway', 'Empangeni');
insert into customer (name, city) values ('Grenville Witts', 'Néa Ionía');
insert into customer (name, city) values ('Damaris Bellchamber', 'Kedungringin');
insert into customer (name, city) values ('Cross Dalla', 'Xiahan');
insert into customer (name, city) values ('Meier Swadlinge', 'Jiangchuan');
insert into customer (name, city) values ('Karleen McGahern', 'Río Ceballos');
insert into customer (name, city) values ('Stacee Roselli', 'Roodepoort');
insert into customer (name, city) values ('Edin Longworthy', 'Marsa Alam');
insert into customer (name, city) values ('Rees MacGinlay', 'Pom Prap Sattru Phai');
insert into customer (name, city) values ('Nelly Emsley', 'Mariscala');
insert into customer (name, city) values ('Pasquale Roscam', 'Bellavista');
insert into customer (name, city) values ('Mikol Isley', 'Czudec');
insert into customer (name, city) values ('Gregory Antoszewski', 'Ngedhusuba');
insert into customer (name, city) values ('Cortie Westpfel', 'Kaura Namoda');
insert into customer (name, city) values ('Lane Bearham', 'Głuchów');
insert into customer (name, city) values ('Reggie Raveau', 'Loshnitsa');
insert into customer (name, city) values ('Darcie Merrien', 'Xiyuan');
insert into customer (name, city) values ('Rodrick Isaacs', 'Khawr Maksar');
insert into customer (name, city) values ('Kristo Knowlys', 'Niš');
insert into customer (name, city) values ('Roxie Skeath', 'Kampungladang');
insert into customer (name, city) values ('Octavius Skalls', 'Khulm');
insert into customer (name, city) values ('Salvador Blampy', 'Yishi');
insert into customer (name, city) values ('Christan Musicka', 'Nanyang');
insert into customer (name, city) values ('Cyrille Prendiville', 'Xinhe');
insert into customer (name, city) values ('Vida Clouter', 'Gia Ray');
insert into customer (name, city) values ('Shea Semark', 'Nova Venécia');
insert into customer (name, city) values ('Dave Saldler', 'Leuwihalang');
insert into customer (name, city) values ('Ber Coskerry', 'Pejukutan');
insert into customer (name, city) values ('Willis Giffaut', 'Toronto');
insert into customer (name, city) values ('Felike O''Fallone', 'Bolou');
insert into customer (name, city) values ('Jeniece Portsmouth', 'Yako');
insert into customer (name, city) values ('Tonia Boyack', 'Taltal');
insert into customer (name, city) values ('Berke Ferencowicz', 'Hebu');
insert into customer (name, city) values ('Doy Isham', 'Las Flores');
insert into customer (name, city) values ('Gerrilee Elcy', 'Mastaiciai');
insert into customer (name, city) values ('Barton Sylett', 'Qimantage');
insert into customer (name, city) values ('Orin Cheesman', 'Santa Maria');
insert into customer (name, city) values ('Normand MacCourt', 'Pushkinskiye Gory');
insert into customer (name, city) values ('Elbert Gogie', 'Jinsha');
insert into customer (name, city) values ('Maribelle Cars', 'Stare Miasto');
insert into customer (name, city) values ('Stirling Sheekey', 'Arrap’i');
insert into customer (name, city) values ('Jarred Grogono', 'Bayonne');
insert into customer (name, city) values ('Ninnetta Durden', 'Pescadería');
insert into customer (name, city) values ('Rubetta Butterley', 'Margahayukencana');
insert into customer (name, city) values ('Donaugh Jeandin', 'Wu’erqihan');
insert into customer (name, city) values ('Seumas Lemmer', 'La Fortuna');
insert into customer (name, city) values ('Adda Dibner', 'San Rafael Petzal');
insert into customer (name, city) values ('Royall Hazlehurst', 'Ovacik');
insert into customer (name, city) values ('Fannie Kelly', 'Glendale');
insert into customer (name, city) values ('Esdras Wigzell', 'Fernández');
insert into customer (name, city) values ('Nicholas Titcom', 'Obninsk');
insert into customer (name, city) values ('Janelle Duprey', 'Moneghetti');
insert into customer (name, city) values ('Anastasie Oldroyde', 'Xinzhu');
insert into customer (name, city) values ('Virgie Robbs', 'Huangsha');
insert into customer (name, city) values ('Druci Kyttor', 'Tanashichō');
insert into customer (name, city) values ('Ginelle Lambot', 'Kanoni');
insert into customer (name, city) values ('Evangelin Perell', 'Bečej');
insert into customer (name, city) values ('Lanae Donaher', 'Nanhe');
insert into customer (name, city) values ('Niel Cranstone', 'Berkovitsa');
insert into customer (name, city) values ('Grete Withers', 'Nagykanizsa');
insert into customer (name, city) values ('Raf MacKeig', 'Fenlu');
insert into customer (name, city) values ('Huberto Swan', 'Anhua Daying');
insert into customer (name, city) values ('Jourdan Weymouth', 'Roanoke');
insert into customer (name, city) values ('Ervin Nicol', 'Vuhlehirs’k');
insert into customer (name, city) values ('Patrica Scade', 'Sukorejo');
insert into customer (name, city) values ('Risa Habin', 'Koppies');
insert into customer (name, city) values ('Amelina Windaybank', 'Nurabelen');
insert into customer (name, city) values ('Irene Palser', 'Lajinha');
insert into customer (name, city) values ('Irena Bassingham', 'Linhares');
insert into customer (name, city) values ('Helenka Kennford', 'Plato');
insert into customer (name, city) values ('Darrick Oxbe', 'Mpigi');
insert into customer (name, city) values ('Caryn Lates', 'Labuhanlalar');
insert into customer (name, city) values ('Egor Nel', 'Chazón');
insert into customer (name, city) values ('Cari Wellsman', 'Keboireng');
insert into customer (name, city) values ('Patsy Smaling', 'Nikolayevka');
insert into customer (name, city) values ('Hazel Bariball', 'Dongtuan');
insert into customer (name, city) values ('Edgardo Morit', 'Tirapata');
insert into customer (name, city) values ('Tiebold Wenderott', 'Jatirogo');
insert into customer (name, city) values ('Fidole Stallon', 'Badīn');
insert into customer (name, city) values ('Latrena Thrush', 'Al Qurḩ');
insert into customer (name, city) values ('Sacha Lile', 'Carvalhal');
insert into customer (name, city) values ('Bobby Linay', 'Bojong');
insert into customer (name, city) values ('Casar Spencley', 'Jiangkou');
insert into customer (name, city) values ('Natalya Manus', 'Duotian');
insert into customer (name, city) values ('Merrili Mayfield', 'Nīkshahr');
insert into customer (name, city) values ('Mirabel Iashvili', 'Suwaru');
insert into customer (name, city) values ('Seward Gribbell', 'Chenqing');
insert into customer (name, city) values ('Kaitlyn Fiddler', 'Koźle');
insert into customer (name, city) values ('Lavena Irvin', 'Nowa Ruda');
insert into customer (name, city) values ('Brena Wickstead', 'Inglewood');
insert into customer (name, city) values ('Doralyn Blodget', 'Nysa');
insert into customer (name, city) values ('Marina Sprigging', 'Palmeira');
insert into customer (name, city) values ('Fey MacGuigan', 'IJmuiden');
insert into customer (name, city) values ('Antonietta Storrock', 'Pulau Pinang');
insert into customer (name, city) values ('Sandi Izatson', 'Fu’an');
insert into customer (name, city) values ('Ibby McQuirk', 'Watuweri');
insert into customer (name, city) values ('Rochester Edelman', 'Härnösand');
insert into customer (name, city) values ('Wilt Gaskall', 'Jinping');
insert into customer (name, city) values ('Culver Loadwick', 'Pirassununga');
insert into customer (name, city) values ('Lavena See', 'Salaverry');
insert into customer (name, city) values ('Francene Drife', 'Turgun');
insert into customer (name, city) values ('Charlie Baddiley', 'Huangtugang');
insert into customer (name, city) values ('Leelah Posnette', 'Shardara');
insert into customer (name, city) values ('Waiter Brydone', 'Shekou');
insert into customer (name, city) values ('Sylvester Twede', 'San Antonio Aguas Calientes');
insert into customer (name, city) values ('Jeniece Chadwell', 'Honjō');
insert into customer (name, city) values ('Emanuele Rosencwaig', 'Lille');
insert into customer (name, city) values ('Harriot Stiling', 'Timashëvsk');
insert into customer (name, city) values ('Emeline Shillam', 'Isnos');
insert into customer (name, city) values ('Lek Kleinhaus', 'Smolec');
insert into customer (name, city) values ('Vikky Huckster', 'Kristinehamn');
insert into customer (name, city) values ('Jasen Danielot', 'Sakata');
insert into customer (name, city) values ('Kristina Halliburton', 'Dukla');
insert into customer (name, city) values ('Rog Juggings', 'Zhongxin');
insert into customer (name, city) values ('Adelheid Chansonnau', 'Épinal');
insert into customer (name, city) values ('Elliot Helstrip', 'Chuqui Chuqui');
insert into customer (name, city) values ('Nedda Wildbore', 'Al Jafr');
insert into customer (name, city) values ('Cesaro Bold', 'Askaniya Nova');
insert into customer (name, city) values ('Fay Synnott', 'Pietermaritzburg');
insert into customer (name, city) values ('Sarena Vallentin', 'Sarāb');
insert into customer (name, city) values ('Conroy Fieller', 'Kura');
insert into customer (name, city) values ('Ted Ogelsby', 'Matsudo');
insert into customer (name, city) values ('Kasper O''Dreain', 'Zárate');
insert into customer (name, city) values ('Keely Farrer', 'Jianghong');
insert into customer (name, city) values ('Abigale Mearing', 'Atocha');
insert into customer (name, city) values ('Alfy Linbohm', 'Shenzhengqiao');
insert into customer (name, city) values ('Yule Petford', 'Leon Postigo');
insert into customer (name, city) values ('Marilee Horry', 'Andrijevica');
insert into customer (name, city) values ('Lynnea Dannatt', 'Dengjiang');
insert into customer (name, city) values ('Keary Dumphrey', 'Kenitra');
insert into customer (name, city) values ('Boyce Paddemore', 'Nobres');
insert into customer (name, city) values ('Fanya Saville', 'Ina');
insert into customer (name, city) values ('Melodee Askie', 'Hikari');
insert into customer (name, city) values ('Gwyneth Godehard.sf', 'Outeiro');
insert into customer (name, city) values ('Selestina Mitcham', 'Ban Houakhoua');
insert into customer (name, city) values ('Laurice Leggett', 'Hanyin Chengguanzhen');
insert into customer (name, city) values ('Lolly Autin', 'Weru');
insert into customer (name, city) values ('Jesus Iannazzi', 'Umeå');
insert into customer (name, city) values ('Johnathan Tremathick', 'Zhanggongmiao');
insert into customer (name, city) values ('Merell Tebb', 'Candoni');
insert into customer (name, city) values ('Lisle Peerless', 'Piran');
insert into customer (name, city) values ('Kaycee Gwilym', 'Krajan Karangsari');
insert into customer (name, city) values ('Terrijo Petz', 'Guilmaro');
insert into customer (name, city) values ('Hi Zorzi', 'Kalmar');
insert into customer (name, city) values ('Bennie Sturm', 'Bryansk');
insert into customer (name, city) values ('Art Jewks', 'San Diego');
insert into customer (name, city) values ('Sigrid Batrim', 'Odoyev');
insert into customer (name, city) values ('Perry Harriskine', 'Dingcheng');
insert into customer (name, city) values ('Tracy Kibbee', 'Ersekë');
insert into customer (name, city) values ('Lewes Bowlands', 'Bantian');
insert into customer (name, city) values ('Mersey Mulvy', 'Krajan Demit');
insert into customer (name, city) values ('Emma Bartelli', 'Jabat');
insert into customer (name, city) values ('Tad Patkin', 'Jarash');
insert into customer (name, city) values ('Ameline Borleace', 'Naperville');
insert into customer (name, city) values ('Suzi Crossgrove', 'Labuhantanggabesar');
insert into customer (name, city) values ('Evaleen Jaqueminet', 'Bandhagen');
insert into customer (name, city) values ('Yorke Popplewell', 'Drachten');
insert into customer (name, city) values ('Zak Samper', 'Cachoeirinha');
insert into customer (name, city) values ('Christiane Werendell', 'Lameiro');
insert into customer (name, city) values ('Wendy Anfosso', 'Sijunjung');
insert into customer (name, city) values ('Faith Dayes', 'Peña Blanca');
insert into customer (name, city) values ('Ilse Ughi', 'Vergara');
insert into customer (name, city) values ('Erie Taylorson', 'Mekele');
insert into customer (name, city) values ('Ogdan Ciciotti', 'Lipahan');
insert into customer (name, city) values ('Hale Purser', 'Miguel Aleman');
insert into customer (name, city) values ('Freddie Camber', 'Calauan');
insert into customer (name, city) values ('Curtis Meaton', 'Pácora');
insert into customer (name, city) values ('Ced Crampsy', 'Monroe');
insert into customer (name, city) values ('Olav Winteringham', 'Bodø');
insert into customer (name, city) values ('Onfre Lingley', 'Azacualpa');
insert into customer (name, city) values ('Leontine Mitford', 'Quesada');
insert into customer (name, city) values ('Vivien Burdass', 'Sparks');
insert into customer (name, city) values ('Sharline Twaite', 'Juiz de Fora');
insert into customer (name, city) values ('Viviene Purton', 'Xinzhuang');
insert into customer (name, city) values ('Andromache Brownsmith', 'Tawun');
insert into customer (name, city) values ('Constantia Doogood', 'Mojo');
insert into customer (name, city) values ('Thomasine Boays', 'Syriam');
insert into customer (name, city) values ('Tibold Doe', 'Katima Mulilo');
insert into customer (name, city) values ('Mavis Maccrae', 'Sopron');
insert into customer (name, city) values ('Rochelle Kemster', 'Valdice');
insert into customer (name, city) values ('Brent Halburton', 'Biguaçu');
insert into customer (name, city) values ('Gunther Heffron', 'Nangong');
insert into customer (name, city) values ('Rosaline Duffree', 'Izyaslav');
insert into customer (name, city) values ('Elenore Bisatt', 'Ōiso');
insert into customer (name, city) values ('Lisa Goulter', 'San Diego');
insert into customer (name, city) values ('Bary Earles', 'Prakhon Chai');
insert into customer (name, city) values ('Rici Tuther', 'Chichinales');
insert into customer (name, city) values ('Julie Bunce', 'Balkanabat');
insert into customer (name, city) values ('Georgina Lodge', 'Yujia’ao');
insert into customer (name, city) values ('Rube Donaghie', 'Staryy Oskol');
insert into customer (name, city) values ('Haven Cruxton', 'Tangwāni');
insert into customer (name, city) values ('Marsh Yggo', 'Bayang');
insert into customer (name, city) values ('Harv Robertot', 'Corbeil-Essonnes');
insert into customer (name, city) values ('Carney Stealfox', 'Yangce');
insert into customer (name, city) values ('Bert Basler', 'Huajlaya');
insert into customer (name, city) values ('Skell Sommerlin', 'Viraco');
insert into customer (name, city) values ('Andria Hintze', 'Hotonj');
insert into customer (name, city) values ('Brenn Hickisson', 'Dawu');
insert into customer (name, city) values ('Bailey Upcott', 'Bezons');
insert into customer (name, city) values ('Gardy Coldbath', 'Olavarría');
insert into customer (name, city) values ('Barn Suffe', 'Seaforth');
insert into customer (name, city) values ('Devondra Glasebrook', 'Polyarnyy');
insert into customer (name, city) values ('Darcie Meininking', 'Arrepiado');
insert into customer (name, city) values ('Roxie Conkey', 'Zhangguanying');
insert into customer (name, city) values ('Clarey Sprules', 'Madang');
insert into customer (name, city) values ('Raina Gilfoyle', 'Kostanay');
insert into customer (name, city) values ('Elsy Larret', 'Tchintabaraden');
insert into customer (name, city) values ('Rosa Harry', 'Masindi Port');
insert into customer (name, city) values ('Timothy Gutans', 'Los Rastrojos');
insert into customer (name, city) values ('Jessee Billyard', 'Pasadena');
insert into customer (name, city) values ('Evelin McGilben', 'Dijon');
insert into customer (name, city) values ('Beryl Marney', 'Choros');
insert into customer (name, city) values ('Harvey Hallen', 'Juan L. Lacaze');
insert into customer (name, city) values ('Damiano Khalid', 'Areia Branca');
insert into customer (name, city) values ('Derwin Menichi', 'Arjawinangun');
insert into customer (name, city) values ('Fanchette Goff', 'Oussivo');
insert into customer (name, city) values ('Caritta Heller', 'Brotas');
insert into customer (name, city) values ('Nadean Deason', 'Pilar do Sul');
insert into customer (name, city) values ('Inna Le Pruvost', 'Yijiang');
insert into customer (name, city) values ('Dina Puncher', 'Petushki');
insert into customer (name, city) values ('Saloma Dacks', 'Struga');
insert into customer (name, city) values ('Kimberlee Wilce', 'Gurung');
insert into customer (name, city) values ('Kaylee Grissett', 'Khafizan');
insert into customer (name, city) values ('Juan Acey', 'Kuala Lumpur');
insert into customer (name, city) values ('Janette Jacobbe', 'Labansari');
insert into customer (name, city) values ('Ameline Aldgate', 'Izborsk');
insert into customer (name, city) values ('Lelah Sloper', 'Dongpu');
insert into customer (name, city) values ('Dulcy Voce', 'Boston');
insert into customer (name, city) values ('Karlee Rillstone', 'Krajan');
insert into customer (name, city) values ('Rosanne Sodor', 'Tolstoy-Yurt');
insert into customer (name, city) values ('Ezechiel Campagne', 'Izyum');
insert into customer (name, city) values ('Jacquette Soutter', 'Mata');
insert into customer (name, city) values ('Renee Veracruysse', 'Lendava');
insert into customer (name, city) values ('Thorny Daftor', 'Orly');
insert into customer (name, city) values ('Michell Janatka', 'Tierp');
insert into customer (name, city) values ('Chaddy Olufsen', 'Jiuhua');
insert into customer (name, city) values ('Belia Sirette', 'Enrekang');
insert into customer (name, city) values ('Gavrielle Fullerd', 'Maisí');
insert into customer (name, city) values ('Galvan Pirnie', 'Berbek');
insert into customer (name, city) values ('Roscoe Daventry', 'Waco');
insert into customer (name, city) values ('Geoffrey Beavon', 'Chishtiān Mandi');
insert into customer (name, city) values ('Moina Rraundl', 'Papatowai');
insert into customer (name, city) values ('Ryun Tesmond', 'Baugo');
insert into customer (name, city) values ('Ardyce Burnside', 'Zīrakī');
insert into customer (name, city) values ('Rosalinde Cusick', 'Botao');
insert into customer (name, city) values ('Agnes De Carolis', 'Ogōri-shimogō');
insert into customer (name, city) values ('Anneliese Fronczak', 'Bangkal');
insert into customer (name, city) values ('Graham Lyles', 'Balagui');
insert into customer (name, city) values ('Courtney Menere', 'Volodymyr-Volyns’kyy');
insert into customer (name, city) values ('Karia Blaisdell', 'Sankanan');
insert into customer (name, city) values ('Guthry Portail', 'João Câmara');
insert into customer (name, city) values ('Irene Tethacot', 'Kirkkonummi');
insert into customer (name, city) values ('Doralin Mullin', 'Palkovice');
insert into customer (name, city) values ('Dell Scyner', 'Cibenda');
insert into customer (name, city) values ('Annette Peller', 'Maych’ew');
insert into customer (name, city) values ('Knox Piell', 'Umm Sa‘īd');
insert into customer (name, city) values ('Tansy Whittek', 'Babakan');
insert into customer (name, city) values ('Ly Fountain', 'Oetuke');
insert into customer (name, city) values ('Bryanty Yusupov', 'Tinabogan');
insert into customer (name, city) values ('Lawry Ockenden', 'Kokagax');
insert into customer (name, city) values ('Jewel Wyllcocks', 'Tutup');
insert into customer (name, city) values ('Ketti Hatfull', 'Quilino');
insert into customer (name, city) values ('April Joret', 'Changling');
insert into customer (name, city) values ('Rose Bengochea', 'Yulin');
insert into customer (name, city) values ('Gallard Faulconbridge', 'Kotabesi');
insert into customer (name, city) values ('Modesty Annott', 'Piippola');
insert into customer (name, city) values ('Ludovico Sidwick', 'Sibulan');
insert into customer (name, city) values ('Sigmund Mowling', 'Póvoa');
insert into customer (name, city) values ('Eadith Corcoran', 'Waldbredimus');
insert into customer (name, city) values ('Iggie Goering', 'Sirnarasa');
insert into customer (name, city) values ('Nichol Bengough', 'Shiye');
insert into customer (name, city) values ('Laney Wrout', 'Lobatse');
insert into customer (name, city) values ('Esteban Bethune', 'Uppsala');
insert into customer (name, city) values ('Tanhya Bewshea', 'Pulangbato');
insert into customer (name, city) values ('Percy Ellis', 'Garisul');
insert into customer (name, city) values ('Ardine Wolfers', 'Randusari');
insert into customer (name, city) values ('Koralle Bridger', 'Lalagsan');
insert into customer (name, city) values ('Kylie Vardy', 'Maxiao');
insert into customer (name, city) values ('Noami Giamuzzo', 'Bordeaux');
insert into customer (name, city) values ('Ddene Peasegod', 'Muzhou');
insert into customer (name, city) values ('Marwin Heaffey', 'Guyi');
insert into customer (name, city) values ('Christiane Matteo', 'Mintang');
insert into customer (name, city) values ('Valencia O''Gready', 'Wutun');
insert into customer (name, city) values ('Oran Wolstencroft', 'Sabon Gari-Nangere');
insert into customer (name, city) values ('Winfred Fewtrell', 'Daduchuan');
insert into customer (name, city) values ('Allsun Mc Cahey', 'Sukadami');
insert into customer (name, city) values ('Hanan Formilli', 'Jungkat Selatan');
insert into customer (name, city) values ('Livy Veevers', 'Baylo');
insert into customer (name, city) values ('Preston Zollner', 'Sepanjang');
insert into customer (name, city) values ('Zacherie Zamorano', 'Osilnica');
insert into customer (name, city) values ('Jeanette Chatelot', 'Palebunan');
insert into customer (name, city) values ('Quinn Chartres', 'Ughelli');
insert into customer (name, city) values ('Vic Galler', 'Montijo');
insert into customer (name, city) values ('Rip Meeland', 'Linxia Chengguanzhen');
insert into customer (name, city) values ('Alika Jonas', 'Fuxing');
insert into customer (name, city) values ('Beau Leeds', 'Jiaoshanhe');
insert into customer (name, city) values ('Darcee Snodin', 'Patsi');
insert into customer (name, city) values ('Marie-ann Cornu', 'Ayabe');
insert into customer (name, city) values ('Nappy MacMeanma', 'Daduchuan');
insert into customer (name, city) values ('Gretal Lardner', 'Konotop');
insert into customer (name, city) values ('Marlon Romer', 'Čáslav');
insert into customer (name, city) values ('Adena Pattillo', 'Gnojnik');
insert into customer (name, city) values ('Verena Belding', 'Yur’yevets');
insert into customer (name, city) values ('Steven Cardno', 'Nishiwaki');
insert into customer (name, city) values ('Ignacio Risely', 'Qulsary');
insert into customer (name, city) values ('Bennie Rozenbaum', 'Huangqi');
insert into customer (name, city) values ('Xena Strass', 'Guanyinsi');
insert into customer (name, city) values ('Patric Mongan', 'Chernivtsi');
insert into customer (name, city) values ('Darcie Dumbare', 'Ai Tu');
insert into customer (name, city) values ('Nertie Emanson', 'Al Ḩarāk');
insert into customer (name, city) values ('Lisette Evenett', 'Maubin');
insert into customer (name, city) values ('Granny Wenzel', 'Qārah');
insert into customer (name, city) values ('Eimile Gaucher', 'Khodasy');
insert into customer (name, city) values ('Ashlie Riepel', 'Tak');
insert into customer (name, city) values ('Cooper Brettel', 'Tapera');
insert into customer (name, city) values ('Ailsun Sutherel', 'Kupang');
insert into customer (name, city) values ('Frederigo Matteau', 'Palmira');
insert into customer (name, city) values ('Farah Josse', 'Cisaro');
insert into customer (name, city) values ('Ritchie Baumer', 'Danao');
insert into customer (name, city) values ('Job Fonso', 'La Cocha');
insert into customer (name, city) values ('Nevsa Clayborn', 'Marietta');
insert into customer (name, city) values ('Martyn Rumney', 'Zabrze');
insert into customer (name, city) values ('Maryjane Tofpik', 'Pajagan');
insert into customer (name, city) values ('Katy Stratford', 'Texíguat');
insert into customer (name, city) values ('Janene Hardy', 'Vatutino');
insert into customer (name, city) values ('Astrid Danhel', 'Medicine Hat');
insert into customer (name, city) values ('Brook Laimable', 'Buyun');
insert into customer (name, city) values ('Obie Snelling', 'Manning');
insert into customer (name, city) values ('Revkah Tindle', 'Shangkuli');
insert into customer (name, city) values ('Grier Le Monnier', 'Douba');
insert into customer (name, city) values ('Ethelbert Langmead', 'Currais');
insert into customer (name, city) values ('Salaidh Happer', 'Daluo');
insert into customer (name, city) values ('Taddeusz Waldie', 'Banaran');
insert into customer (name, city) values ('Ralina Landell', 'Krzepice');
insert into customer (name, city) values ('Suzanna Snarr', 'Paterson');
insert into customer (name, city) values ('Matt Hardway', 'Quţūr');
insert into customer (name, city) values ('Francklin Braham', 'Chatuchak');
insert into customer (name, city) values ('Chick Gras', 'Suileng');
insert into customer (name, city) values ('Nobe Grabham', 'Bauang');
insert into customer (name, city) values ('Jewell Mayworth', 'Roa');
insert into customer (name, city) values ('Karylin Rivard', 'Guanbuqiao');
insert into customer (name, city) values ('Grissel Arrol', 'Barrancas');
insert into customer (name, city) values ('Erminia Roffey', 'Saskatoon');
insert into customer (name, city) values ('Murray Brassington', 'Awjilah');
insert into customer (name, city) values ('Moshe Finessy', 'Tierp');
insert into customer (name, city) values ('Veronica Acheson', 'Ludishan');
insert into customer (name, city) values ('Carly Nuschke', 'Longshi');
insert into customer (name, city) values ('Man Medd', 'Brescia');
insert into customer (name, city) values ('Mathilde Trymme', 'Guisijan');
insert into customer (name, city) values ('Franzen Badam', 'Greenwood');
insert into customer (name, city) values ('Rubina Phair', 'Emiliano Zapata');
insert into customer (name, city) values ('Prisca Babst', 'Brongkalan');
insert into customer (name, city) values ('Sylvan Mounsey', 'Ozatlán');
insert into customer (name, city) values ('Ethyl MacKessock', 'Xinglong');
insert into customer (name, city) values ('Melisenda Pykerman', 'Yirshi');
insert into customer (name, city) values ('Ham Rowlinson', 'Uvarovo');
insert into customer (name, city) values ('Pegeen Burker', 'Independencia');
insert into customer (name, city) values ('Mara Augie', 'Güira de Melena');
insert into customer (name, city) values ('Perrine Earland', 'Kinsealy-Drinan');
insert into customer (name, city) values ('Udell Currier', 'Abengourou');
insert into customer (name, city) values ('Germana Bisatt', 'Babice');
insert into customer (name, city) values ('Myrah Stannett', 'Washington');
insert into customer (name, city) values ('Margot Bonnefin', 'Krajan Baru');
insert into customer (name, city) values ('Domingo Wettern', 'Keetmanshoop');
insert into customer (name, city) values ('Sebastien Downer', 'Xufu');
insert into customer (name, city) values ('Morgen Beachamp', 'Ila Orangun');
insert into customer (name, city) values ('Anton Pahl', 'Weru');
insert into customer (name, city) values ('Lilas Luckett', 'Przemęt');
insert into customer (name, city) values ('Violet Reuble', 'Phra Phrom');
insert into customer (name, city) values ('Gaile Rallinshaw', 'Geneng Tengah');
insert into customer (name, city) values ('Goldia Soffe', 'Mercier');
insert into customer (name, city) values ('Erica Merton', 'Banjarkemuning');
insert into customer (name, city) values ('Fred Neumann', 'La Tour-du-Pin');
insert into customer (name, city) values ('Shelby Bligh', 'Karmai');
insert into customer (name, city) values ('Orren Cullen', 'Jacareí');
insert into customer (name, city) values ('Sig Norrey', 'Mpumalanga');
insert into customer (name, city) values ('Truda Brimilcome', 'Krasnolesnyy');
insert into customer (name, city) values ('Jaclin Diable', 'Tomislavgrad');
insert into customer (name, city) values ('Tana McClure', 'Kiruru');
insert into customer (name, city) values ('Baxter Bland', 'Takaoka');
insert into customer (name, city) values ('Rahal McIlwrick', 'Matwaḩ');
insert into customer (name, city) values ('Koenraad Collcutt', 'Thoen');
insert into customer (name, city) values ('Clarisse Moodie', 'Caluire-et-Cuire');
insert into customer (name, city) values ('Hadley Penvarne', 'Batasan Bata');
insert into customer (name, city) values ('Terrill Trassler', 'Łobez');
insert into customer (name, city) values ('Udell Linklet', 'Semënov');
insert into customer (name, city) values ('Lane Cossor', 'Los Andes');
insert into customer (name, city) values ('Elwood Louw', 'Nelson');
insert into customer (name, city) values ('Olwen Simond', 'Oussivo');
insert into customer (name, city) values ('Northrup Prowting', 'Sokolo');
insert into customer (name, city) values ('Agnes Mapledoram', 'Liuzhou');
insert into customer (name, city) values ('Dorothee Covington', 'Qinjiang');
insert into customer (name, city) values ('Phoebe McCloid', 'Ojos de Agua');
insert into customer (name, city) values ('Dede Kemery', 'Luofang');
insert into customer (name, city) values ('Monty Woodlands', 'Jacutinga');
insert into customer (name, city) values ('Danila Dodman', 'Stari Bar');
insert into customer (name, city) values ('Dorree Rodie', 'Krajan Rowokangkung');
insert into customer (name, city) values ('Victoria Jakobssen', 'La Calera');
insert into customer (name, city) values ('Madeline Geraudel', 'San Antonio');
insert into customer (name, city) values ('Joli Ledster', 'Jinhe');
insert into customer (name, city) values ('Nathaniel Toler', 'Umm Kaddadah');
insert into customer (name, city) values ('Ardenia Ganders', 'Chigorodó');
insert into customer (name, city) values ('Camey Pedley', 'Suicheng');
insert into customer (name, city) values ('Alano O''Codihie', 'El Paso');
insert into customer (name, city) values ('Mendie Phelp', 'Shanhou');
insert into customer (name, city) values ('Nevin Bugge', 'Maquiapo');
insert into customer (name, city) values ('Boony Edwicke', 'Las Flores');
insert into customer (name, city) values ('Paul Jados', 'Filótion');
insert into customer (name, city) values ('Allyce Verma', 'Kerep Wetan');
insert into customer (name, city) values ('Darryl Espadas', 'Shangmofang');
insert into customer (name, city) values ('Aliza Ewbanche', 'Nakajah');
insert into customer (name, city) values ('Tricia Mingauld', 'Guangyi');
insert into customer (name, city) values ('Birgitta Stowell', 'Saint John');
insert into customer (name, city) values ('Constantina Trippett', 'Piracicaba');
insert into customer (name, city) values ('Oswald Parram', 'Huiwan');
insert into customer (name, city) values ('Mala Brade', 'Frýdlant');
insert into customer (name, city) values ('Morrie Iacovucci', 'Krasnohrad');
insert into customer (name, city) values ('My Maddrell', 'Gardawice');
insert into customer (name, city) values ('Binny Vice', 'Parang');
insert into customer (name, city) values ('Pattie Hulk', 'Liucheng');
insert into customer (name, city) values ('Roseann Cowdry', 'Tuatuka');
insert into customer (name, city) values ('Laryssa Bott', 'Jujur');
insert into customer (name, city) values ('Anthe Sommerly', 'Lat Lum Kaeo');
insert into customer (name, city) values ('Ernestus Zuanazzi', 'Apeldoorn');
insert into customer (name, city) values ('Ozzy Dingley', 'Laiponda');
insert into customer (name, city) values ('Sibyl Butterworth', 'West Palm Beach');
insert into customer (name, city) values ('Cyril Bloyes', 'Yablonovskiy');
insert into customer (name, city) values ('Fionna Maddigan', 'Trashigang');
insert into customer (name, city) values ('Carmelina Priden', 'Zhongxi');
insert into customer (name, city) values ('Douglass Causbey', 'Gózd');
insert into customer (name, city) values ('Culver Glusby', 'Valbonë');
insert into customer (name, city) values ('Hercule Jorden', 'Tysmenychany');
insert into customer (name, city) values ('Weider La Wille', 'Dobra');
insert into customer (name, city) values ('Bertrando Pheby', 'Raheny');
insert into customer (name, city) values ('Corrie Heritege', 'Kalibunder');
insert into customer (name, city) values ('Anestassia Gruczka', 'Fatikchari');
insert into customer (name, city) values ('Care Dunlap', 'Motala');
insert into customer (name, city) values ('Fiann Yeowell', 'Portão');
insert into customer (name, city) values ('Lisetta Splevins', 'Konga');
insert into customer (name, city) values ('Dukey Mitchel', 'Mýto');
insert into customer (name, city) values ('Ashleigh Iseton', 'Mirnyy');
insert into customer (name, city) values ('Wallis Hendrickx', 'Qinhe');
insert into customer (name, city) values ('Dulce Lentsch', 'Ad Dann');
insert into customer (name, city) values ('Siobhan De Cruce', 'Paripiranga');
insert into customer (name, city) values ('Hanna De''Vere - Hunt', 'Chocope');
insert into customer (name, city) values ('Genny Turmall', 'Orahovica');
insert into customer (name, city) values ('Ivonne Westraw', 'Támara');
insert into customer (name, city) values ('Jojo Concannon', 'Baytīn');
insert into customer (name, city) values ('Sadye Yair', 'Ijuí');
insert into customer (name, city) values ('Weylin Burree', 'Karavan');
insert into customer (name, city) values ('Peta Jankowski', 'Potrerillos');
insert into customer (name, city) values ('Reta Skeldon', 'Bailu');
insert into customer (name, city) values ('Anastassia Jeyes', 'Rohia');
